"""Cross-bundle parser type surface (typing-only `Protocol`).

The recursive-descent `Parser` is composed from themed method-bundle
classes (`_BlockLevelMethods`, `_DeclarationsMethods`, …). Each bundle
calls methods that live in *sibling* bundles (e.g. `_block_level` calls
`self._error`, owned by `_utils`) and reads shared instance state
(`self.stream`, `self.source`). For mypy to type-check those
cross-bundle accesses, every bundle inherits `_ParserState`.

Under type checking, `_ParserState` is a `Protocol` declaring the shared
attributes and every cross-bundle method signature, so `self.<anything>`
resolves from inside any bundle. **At runtime it is an empty base
class** — the real implementations live on the bundles and are composed
by `Parser` (`blocks.py`), so a genuinely missing method surfaces as
an ordinary `AttributeError`, not a silent no-op.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, NoReturn

# Maximum recursive-descent nesting depth (block nesting via `_primary`
# and value/paren nesting via `_parse_primary`). Chosen well below the
# CPython stack budget — each nesting level burns several frames, so
# the interpreter's default ~1000-frame limit blows out around a couple
# hundred levels — yet far above any real stylesheet (Bootstrap and the
# conformance corpus stay in the low tens). Exceeding it raises a clean
# `ParseError`; see `_UtilsMethods._descend`.
MAX_PARSE_DEPTH = 150


if TYPE_CHECKING:
    from contextlib import AbstractContextManager
    from typing import Protocol

    from ..ast_nodes import (
        AtRule,
        Call,
        Comment,
        Condition,
        Declaration,
        DetachedRuleset,
        Element,
        Expression,
        Extend,
        MixinArg,
        MixinCall,
        MixinCallStatement,
        Node,
        Ruleset,
        Selector,
        Url,
        Value,
    )
    from ..lexer import Kind, Token, TokenStream
    from ..source import Source

    class _ParserState(Protocol):
        """Structural type of a fully-composed `Parser`: the shared
        instance state plus every method any bundle may call on `self`.

        Each method-bundle inherits this so cross-bundle `self._foo()`
        calls and `self.stream` accesses type-check. `Parser` (which
        combines all bundles) satisfies it; the individual bundles do
        not implement every member, which is fine — only `Parser` is
        ever instantiated.
        """

        # Shared instance state (set in `Parser.__init__`)
        source: Source
        stream: TokenStream
        _seen_comment_indices: set[int]
        # Recursive-descent nesting counter, bounded by `MAX_PARSE_DEPTH`.
        _depth: int
        # Class constant owned by `_GuardsMethods`.
        _CMP_KINDS: frozenset[Kind]

        # _UtilsMethods (parser/_utils.py)
        def _has_ws_before(self, tok: Token) -> bool: ...
        def _descend(self) -> AbstractContextManager[None]: ...
        def _error(self, msg: str, index: int) -> NoReturn: ...
        def _reject_backtick(self, tok: Token) -> NoReturn: ...
        def _read_interpolation(self) -> str: ...
        def _read_balanced(self, open_kind: Kind, close_kind: Kind) -> str: ...
        def _read_until_block_or_end(
            self, *, stop_kinds: tuple[Kind, ...], at_name: str = ...
        ) -> tuple[str, Token]: ...

        # _BlockLevelMethods (parser/_block_level.py)
        def parse(self) -> Ruleset: ...
        def _unexpected_at_top(self, tok: Token) -> NoReturn: ...
        def _primary(self) -> list[Node]: ...
        def _harvest_block_comments(self, tok: Token) -> list[Comment]: ...
        def _block_item(self) -> Node | None: ...
        def _block_lookahead(self) -> str: ...
        def _at_rule(self) -> AtRule: ...

        # _DeclarationsMethods (parser/_declarations.py)
        def _declaration(self) -> Declaration | None: ...
        def _value_started_after_newline(self, start_tok: Token) -> bool: ...
        def _read_declaration_value(self) -> tuple[str, bool, int, str]: ...

        # _SelectorsMethods (parser/_selectors.py)
        def _ruleset(self) -> Ruleset | None: ...
        def _selectors(self) -> list[Selector] | None: ...
        def _parse_extends_in_elements(self, elements: list[Element]) -> tuple[list[Element], list[Extend]]: ...
        def _selector(self) -> Selector | None: ...
        def _element(self, *, has_prev: bool) -> Element | None: ...
        def _read_element_body(self) -> str | None: ...

        # _StatementsMethods (parser/_statements.py)
        def _statement(self) -> MixinCallStatement: ...

        # _ValueExprMethods (parser/_value_expr.py)
        def _value_terminators(self) -> frozenset[Kind]: ...
        def _parse_value_root(self) -> Value: ...
        def _peek_is_ie_filter(self) -> bool: ...
        def _parse_ie_filter_as_anonymous(self, start: int) -> Value: ...
        def _parse_expression(self) -> Expression | None: ...
        def _parse_add_expr(self) -> Node | None: ...
        def _parse_mul_expr(self) -> Node | None: ...
        def _parse_unary(self) -> Node | None: ...
        def _paren_contents_have_top_colon(self) -> bool: ...

        # _ValuePrimaryMethods (parser/_value_primary.py)
        def _parse_primary(self) -> Node | None: ...
        def _parse_anonymous_mixin(self, lead_tok: Token) -> DetachedRuleset: ...

        # _CallsMethods (parser/_calls.py)
        def _parse_call_args(self, start_index: int, name: str) -> Call: ...
        def _parse_call_arg(self) -> Expression | None: ...
        def _parse_namespace_path_or_call(self, start_tok: Token) -> MixinCall: ...
        def _parse_mixin_value_args(self) -> list[MixinArg]: ...
        def _maybe_attach_lookups(self, node: Node) -> Node: ...
        def _parse_lookup_key(self) -> tuple[str, str]: ...
        def _parse_url(self, start_index: int) -> Url: ...

        # _GuardsMethods (parser/_guards.py)
        def _parse_guard_root(self) -> Condition: ...
        def _parse_guard_clause(self) -> Condition: ...
        def _parse_guard_cond(self) -> Condition: ...
        def _parse_guard_and_run(self) -> Condition: ...
        def _parse_guard_and_unit(self) -> Condition: ...
        def _parse_guard_comparison(self) -> Condition: ...

else:

    class _ParserState:
        """Runtime no-op base. The cross-bundle type surface lives in the
        `TYPE_CHECKING` `Protocol` above; at runtime the bundles carry
        the real methods and `Parser` composes them."""

        __slots__ = ()
