"""Evaluation pass split across themed sub-modules.

  * `dispatch`     — `eval_node` + the dispatch table glue
  * `helpers`      — small text / location / important-promotion utilities
  * `values`       — value / expression / call / condition / arithmetic eval
  * `declarations` — `eval_declaration` + value-text classification helpers
  * `rulesets`     — `eval_ruleset`
  * `atrules`      — `eval_atrule` + prelude post-processing
  * `mixins`       — mixin-call invocation, spread, splice tagging
  * `control_flow` — `each`, `if`, variable-call invocation, conditions
  * `lookups`      — `[key]` lookup + `$prop` property access + variables
  * `selectors`    — selector-interpolation pass
  * `imports`      — deferred `@import` resolution

Symbols re-exported below are the package's public surface; prefer
importing from the themed sub-module directly.
"""

from __future__ import annotations

from .._strutil import has_block_comment as _has_preservable_comment
from .atrules import (
    _eval_atrule_prelude,
    _eval_namespace_call_lookups,
    _fold_atrule_prelude_arithmetic,
    _split_top_level_commas,
    eval_atrule,
)
from .control_flow import (
    _apply_negate,
    _as_condition,
    _build_each_frame,
    _each_items,
    _invoke_each,
    _invoke_function_statement,
    _invoke_if_statement,
    _invoke_variable_call,
    _truthy,
    eval_condition,
)
from .declarations import (
    _collect_calls,
    _eagerly_eval_calls_in_variable,
    _eval_declaration_inner,
    _has_comma_without_space,
    _has_high_precision_number,
    _has_missing_leading_zero,
    _has_non_less_value_syntax,
    _has_redundant_decimal_zero,
    _has_unindented_continuation,
    _is_literal_only,
    _split_trailing_block_comment,
    _starts_with_newline,
    _try_eval_custom_property,
    _value_carries_lookup_important,
    _value_contains_url,
    _value_has_evaluable_node,
    eval_declaration,
)
from .dispatch import (
    _EVAL_DISPATCH,
    _build_eval_dispatch,
    _eval_anonymous,
    _eval_identity,
    _eval_lookup_wrap,
    _eval_property_access_wrap,
    _eval_variable_wrap,
    eval_node,
)
from .helpers import (
    _attach_decl_anchor,
    _dim_to_color,
    _extract_var_name,
    _format_call_args,
    _locate,
    _maybe_promote_color,
    _propagate_important,
    _strip_tilde_quotes,
)
from .imports import _resolve_deferred_import
from .lookups import (
    _build_merged_value_text,
    _eval_dr_body,
    _find_property_matches,
    _has_property_decl,
    _is_local_to_dr,
    _lookup_in_rules,
    _lookup_target_is_important,
    _materialize_inner_variables,
    _resolve_lookup_target,
    eval_lookup,
    eval_property_access,
    eval_variable,
)
from .mixins import (
    _arg_has_variable,
    _descent_conditions_pass,
    _expand_spread_call_args,
    _invoke_mixin_call,
    _invoke_value_mixin_call,
    _is_spread_arg,
    _select_mixin_branches,
    _spread_pieces,
    _spread_var_name,
    _tag_splice_closures,
)
from .rulesets import (
    _is_amp_when_block,
    _value_text_has_recursion_trigger,
    eval_ruleset,
)
from .selectors import _eval_selector
from .values import (
    _CALC_LIKE_FUNCTIONS,
    MIXIN_DEPTH_LIMIT,
    MIXIN_TOTAL_LIMIT,
    _and_chain_to_condition,
    _apply,
    _arg_to_condition,
    _cancel,
    _dim_backup,
    _divide_units,
    _eval_boolean,
    _eval_if,
    _eval_isdefined,
    _format_unit,
    _fround,
    _multiply_units,
    _operate_colors,
    _operate_dimensions,
    _set_backup_unit,
    _single_to_condition,
    _split_by_keyword,
    _split_unit,
    _unit_to_condition,
    _unwrap_single,
    _values_to_condition,
    _wrap_values,
    eval_call,
    eval_expression,
    eval_negative,
    eval_operation_inner,
    eval_paren,
    eval_quoted,
    eval_url,
    eval_value,
)

# Populated here so every handler sub-module is imported first;
# otherwise `_build_eval_dispatch` couldn't resolve a handler that
# still lives in a not-yet-imported sub-module.
_build_eval_dispatch()


__all__ = [
    'MIXIN_DEPTH_LIMIT',
    'MIXIN_TOTAL_LIMIT',
    '_CALC_LIKE_FUNCTIONS',
    '_EVAL_DISPATCH',
    '_and_chain_to_condition',
    '_apply',
    '_apply_negate',
    '_arg_has_variable',
    '_arg_to_condition',
    '_as_condition',
    '_attach_decl_anchor',
    '_build_each_frame',
    '_build_eval_dispatch',
    '_build_merged_value_text',
    '_cancel',
    '_collect_calls',
    '_descent_conditions_pass',
    '_dim_backup',
    '_dim_to_color',
    '_divide_units',
    '_each_items',
    '_eagerly_eval_calls_in_variable',
    '_eval_anonymous',
    '_eval_atrule_prelude',
    '_eval_boolean',
    '_eval_declaration_inner',
    '_eval_dr_body',
    '_eval_identity',
    '_eval_if',
    '_eval_isdefined',
    '_eval_lookup_wrap',
    '_eval_namespace_call_lookups',
    '_eval_property_access_wrap',
    '_eval_selector',
    '_eval_variable_wrap',
    '_expand_spread_call_args',
    '_extract_var_name',
    '_find_property_matches',
    '_fold_atrule_prelude_arithmetic',
    '_format_call_args',
    '_format_unit',
    '_fround',
    '_has_comma_without_space',
    '_has_high_precision_number',
    '_has_missing_leading_zero',
    '_has_non_less_value_syntax',
    '_has_preservable_comment',
    '_has_property_decl',
    '_has_redundant_decimal_zero',
    '_has_unindented_continuation',
    '_invoke_each',
    '_invoke_function_statement',
    '_invoke_if_statement',
    '_invoke_mixin_call',
    '_invoke_value_mixin_call',
    '_invoke_variable_call',
    '_is_amp_when_block',
    '_is_literal_only',
    '_is_local_to_dr',
    '_is_spread_arg',
    '_locate',
    '_lookup_in_rules',
    '_lookup_target_is_important',
    '_materialize_inner_variables',
    '_maybe_promote_color',
    '_multiply_units',
    '_operate_colors',
    '_operate_dimensions',
    '_propagate_important',
    '_resolve_deferred_import',
    '_resolve_lookup_target',
    '_select_mixin_branches',
    '_set_backup_unit',
    '_single_to_condition',
    '_split_by_keyword',
    '_split_top_level_commas',
    '_split_trailing_block_comment',
    '_split_unit',
    '_spread_pieces',
    '_spread_var_name',
    '_starts_with_newline',
    '_strip_tilde_quotes',
    '_tag_splice_closures',
    '_truthy',
    '_try_eval_custom_property',
    '_unit_to_condition',
    '_unwrap_single',
    '_value_carries_lookup_important',
    '_value_contains_url',
    '_value_has_evaluable_node',
    '_value_text_has_recursion_trigger',
    '_values_to_condition',
    '_wrap_values',
    'eval_atrule',
    'eval_call',
    'eval_condition',
    'eval_declaration',
    'eval_expression',
    'eval_lookup',
    'eval_negative',
    'eval_node',
    'eval_operation_inner',
    'eval_paren',
    'eval_property_access',
    'eval_quoted',
    'eval_ruleset',
    'eval_url',
    'eval_value',
    'eval_variable',
]
